title: FinChato
baseline: Economic Data Made Simple
description: 'One stop source of all economic data, verified.'
baseurl: /
canonicalurl: true
googleAnalytics: UA-53965395-5
theme: hyde
params:
  themeColor: "theme-base-08"
date:
  format: j F Y
  timezone: Europe/Paris
pagination:
  max: 5
  path: page
output:
  formats:
    netlify_redirects:
      extension: ''
      mediatype: text/plain
virtualpages:
  _redirects:
    output: netlify_redirects
  admin:
    layout: admin/index
    title: Content Manager (Netlify CMS)
    output: html
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
